### ISSUE TITLE
Use parentheses to clarify the scope of words in an English sentence

### ISSUE THREAD

**Issue by GaurangTandon** [ridiculousfish/cdecl-blocks#11]
Very long English sentences, without punctuation and replete with conjunctions, can have more than one unintentional meanings. Consider the current example sentence. It can be interpreted as, or at least I find it interpretable as,

> declare x as array 3 of pointer (to function returning pointer to array 5 of char)
> declare x as array 3 of pointer to function, returning pointer to array 5 of char

As you can see, putting some basic punctuation can have a significant effect on the meaning.

Is it possible to support punctuation in such cases?

**Comment by ridiculousfish** [comment]
I don't understand the second case - what is an "array 3...returning pointer to array 5 of char?" I'm not sure the English has any ambiguities.

**Comment by GaurangTandon** [comment]
Ah, I was mistaken then. Indeed, the second statement is probably nonsensical. That implicitly leaves us with the first sentence as being correct.

Apologies for the trouble!
