### ISSUE TITLE
bad character '-'

### ISSUE THREAD

**Issue by corburn** [ridiculousfish/cdecl-blocks#2]
```C
// syntax error
#define TCP_SKB_CB(__skb) ((struct tcp_skb_cb *)&((__skb)->cb[0]))

// bad character '-'
((struct tcp_skb_cb *)&((__skb)->cb[0]))
```

The above snippet was copied from _Understanding Linux Network Internals_.
It is a type cast for writing data to a socket buffer control buffer.

**Comment by ridiculousfish** [comment]
Do I understand that you pasted this into cdecl and got the above error? cdecl understands C declarations, but not preprocessor defines or other C constructs. In this case it's erroring on the `->` operator.

**Comment by corburn** [comment]
Yes, I incorrectly assumed it should understand these.

**Comment by Eternalinfinity** [comment]
I pasted a program into cdecl and it told me syntax error
https://github.com/Leurak/MEMZ/blob/master/WindowsTrojan/Source/Destructive/ProcessWatchdog.c
