### ISSUE TITLE
bad character '+'  When the parameter definition is unknown

### ISSUE THREAD

**Issue by BearJean** [ridiculousfish/cdecl-blocks#23]
(((Thread_Local_Variables * ) ((char * ) & scheme_thread_locals_space + scheme_tls_delta ) ) -> scheme_current_thread_ ) -> gmp_tls

the 
Thread_Local_Variables 
scheme_thread_locals_space 
scheme_tls_delta 
scheme_current_thread_  
gmp_tls
is definition in project,in that case ,can I can't use this tool ?

**Comment by ridiculousfish** [comment]
No, cdecl does not know about thread local variables. Thanks for filing.
