### ISSUE TITLE
Released version has disappeared

### ISSUE THREAD

**Issue by fxcoudert** [ridiculousfish/cdecl-blocks#3]
Mac Homebrew used to build cdecl from the source at `http://cdecl.org/files/cdecl-blocks-2.5.tar.gz`, but the file has disappeared. Where are you now hosting the 2.5 release source?

**Comment by ridiculousfish** [comment]
Hmm, can it just be pulled from this repo?

**Comment by fxcoudert** [comment]
No, Homebrew only packages software with released versions / a release mechanism.

**Comment by ridiculousfish** [comment]
I've restored the link. Thanks for letting me know!
