### ISSUE TITLE
Simple code doesn't work?

### ISSUE THREAD

**Issue by Heath123** [ridiculousfish/cdecl-blocks#31]
I'm probably not using this properly, but any code I try doesn't work. Even something as simple as
`int a = 1;`
on the site tells me
`bad character '='`

**Comment by Heath123** [comment]
The only things that seem to work properly are variable declaration with no value?

**Comment by ridiculousfish** [comment]
Yes, it only handles declarations, not initializers.

**Comment by Heath123** [comment]
What exactly does this support? Nothing I try seems to work, is there a list of the types of things that are supported so I can try to trim the code own to that?

**Comment by ridiculousfish** [comment]
Supported types are from C89: integer types and floating point types, structs and unions (tag name only, no definitions), and arrays, pointers, function pointers, plus Apple's block syntax extension. Try some of the examples at the top of the page. Note this is very old code.
