### ISSUE TITLE
Release archive no longer available

### ISSUE THREAD

**Issue by p-linnane** [ridiculousfish/cdecl-blocks#37]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We noticed the cdecl archive which was located at https://cdecl.org/files/cdecl-blocks-2.5.tar.gz has been removed. I wanted to see if there was an alternate way to fetch this archive.

Related to
https://github.com/Homebrew/homebrew-core/pull/125712
https://github.com/ridiculousfish/cdecl-blocks/issues/3

**Comment by ridiculousfish** [comment]
Hi Patrick,

I've restored the file. Thanks for letting me know!

-Peter

**Comment by p-linnane** [comment]
Thanks!
