### ISSUE TITLE
Syntax error on function pointer returning function pointer.

### ISSUE THREAD

**Issue by mahesh-hegde** [ridiculousfish/cdecl-blocks#38]
`int (*(*functionReturningFunction)(int a, int b))(int c, int d);`

**Comment by ridiculousfish** [comment]
Yes, cdecl is C parsing code from the 70s. It doesn't like extra identifiers in declarations. If you remove the variable names [it works](https://cdecl.org/?q=int+%28*%28*functionReturningFunction%29%28int%2C+int%29%29%28int%2C+int%29).

**Comment by mahesh-hegde** [comment]
Didn't know. Thought it was C99 or some recent level. Thanks for clarification.
