### ISSUE TITLE
function pointers

### ISSUE THREAD

**Issue by Osteri** [ridiculousfish/cdecl-blocks#5]
Hi,

`void*(*f)(size_t)` is recognized as 

> declare f as pointer to function (size_t) returning pointer to void

but

`void*(*)(size_t)` isn't recognized. I'm not sure if this is a bug or not, both valid C. Is there a reason why not support function pointers without identifiers?

**Comment by dhouck** [comment]
In general it seems to only support declarations and casts, not raw types.

**Comment by ridiculousfish** [comment]
dhouck is right. Creaky 70s code! Thanks for filing.
